import = ["/Users/ianlaue/.config/alacritty/themes/alacritty-theme/themes/gruvbox_dark.toml"]

[font]
size = 23

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"
dynamic_padding = true

[window.padding]
x = 7
y = 0

[shell]
program = "/usr/local/bin/bash"
args = ["-l"]

[cursor]
style = "Beam"
blink_interval = 750

