#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# brew packages Mac
# brew install amethyst fzf nvim exa hugo bash-completion@2 newsboat kubectl ripgrep kubectx lazygit tmux derailed/k9s/k9s

# For fonts
# brew tap homebrew/cask-fonts
# brew install --cask font-jetbrains-mono-nerd-font

# ubuntu packages apt
# ripgrep gh

# ubuntu apt neovim setup
# gcc g++ unzip

# ubuntu brew
# fd fzf kubectl kubectx derailed/k9s/k9s

# ubuntu brew for neovim setup
# neovim go lazygit

# ubuntu specific notes
# create symbolic link to neovim from vim. when not using neovim on
# Ubuntu systems, because I use the v alias everywhere.
# sudo ln -sf /usr/bin/vim /usr/bin/nvim

# ubuntu neovim setup
# there is an issue with npm on wsl ubuntu 22. Use this to install npm: https://stackoverflow.com/questions/73673804/npm-show-npm-elf-not-found-error-in-wsl

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/skhd
mkdir -p "$XDG_CONFIG_HOME"/k9s
# mkdir -p "$XDG_CONFIG_HOME"/newsboat
# mkdir -p "$XDG_CONFIG_HOME"/wezterm

# set up git prompt
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME"/bash/git-prompt.sh

# Symbolic links

# ln -s ./.amethyst.yml "$HOME"/.amethyst.yml
ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
# ln -sf "$PWD/newsboat/config" "$XDG_CONFIG_HOME"/newsboat/config
# ln -sf "$PWD/newsboat/urls" "$XDG_CONFIG_HOME"/newsboat/urls

