-- -- local null_ls = require('null-ls')
--
-- local null_ls_status_ok, null_ls = pcall(require, "null-ls")
-- if not null_ls_status_ok then
--     print("WHAHHAHAAHH")
-- 	return
-- end
--
-- local formatting = null_ls.builtins.formatting
-- local diagnostics = null_ls.builtins.diagnostics
--
-- -- https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md
-- null_ls.setup({
--     debug = true,
--     sources = {
--         diagnostics.mypy,
--         diagnostics.ruff,
--         formatting.black.with({
--             extra_args = { "--line-length=120" }
--         }),
--         formatting.isort,
--         formatting.rustfmt,
--         formatting.stylua,
--     }
-- })
