#!/bin/bash

command docker ps --all --format "{{.ID}}\t{{.Names}}\t{{.Ports}}\t{{.Status}}" \
    | (echo -e "CONTAINER_ID\tNAMES\tPORTS\tSTATUS" && cat) \
    | awk '{printf "\033[1;32m%s\t\033[01;38;5;95;38;5;196m\%s\t\033[00m\033[1;34m%s\t\033[01;90m%s %s %s %s %s %s %s\033[00m\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10;}' \
    | column -s$'\t' -t

