#!/bin/bash

_get_repo() {
  echo "$1" | sed -e "s/.git$//" -e "s/.*github.ihs.demonware.net[:/]\(.*\)/\1/"
}

_build_url() {
  local origin branch repo pr_url target
  origin="$(git config --get remote.origin.url)"
  branch="$(git symbolic-ref --short HEAD)"
  repo="$(_get_repo "$origin")"
  pr_url="https://github.ihs.demonware.net/$repo/pull/new"
  target='master'
 # FOR DEBUG --> echo "origin=$origin | branch=$branch | repo=$repo | pr_url=$pr_url | target=$target"
  echo $pr_url/$target...$branch
}

url="$(_build_url "$*")"
if [ "$(uname -s)" = "Darwin" ]; then
  open "$url" 2> /dev/null
else
  xdg-open "$url" > /dev/null 2> /dev/null
fi

